### ISSUE TITLE
PageDown/Up support

### ISSUE THREAD

**Issue by miguelsilva5989** [simonfaltum/p5250#1]
Any idea how to support PageDown/Up key?
I implemented the following functions but doesn't seem to do nothing on the screens:

    def sendPageDown(self):
        """ Send PageDown
        """
        return self.s3270.do('PageDown')
    
    def sendPageUp(self):
        """ Send PageUp
        """
        return self.s3270.do('PageUp')

Key mapping I checked:

https://www.ibm.com/support/knowledgecenter/SSEQ5Y_5.9.0/com.ibm.pcomm.doc/books/html/emulator_reference02.htm?view=kc#ToC_61

Thanks in advance

**Comment by simonfaltum** [comment]
It is already implemented. In the original 5250 protocol, they call it roll up and roll down, so I have called the functions that as well. Solves it for you? :)

rollUp()

Description: Will roll up a table or menu. This is usually mapped to Page Down.
Arguments: none

rollDown()

Description: Will roll down a table or menu. This is usually mapped to Page Up.
Arguments: none

**Comment by miguelsilva5989** [comment]
now that I found the solution myself I see that you have this 😄 
thanks for this!!!
